### ISSUE TITLE
How to automatically accept new reports (report_mig..) using sweave

### ISSUE THREAD

**Issue by SebastienGrall** [MarionLegrandLogrami/stacomiR#2]
When I launch a new compilation of a report, Stacomi ask to accept new calculation of a report_mig. How can I automatically accept it in my script?

**Comment by cedricbriandgithub** [comment]
add ```silent=TRUE``` to the calcul method. Does that fix your problem ?

```r
  stacomi(gr_interface=FALSE,
	  login_window=FALSE,
	  database_expected=TRUE)	
  r_mig_mult=new("report_mig_mult")
  r_mig_mult=choice_c(r_mig_mult,
	  dc=c(5,6,12),
	  taxa=c("Anguilla anguilla"),
	  stage=c("AGG","AGJ","CIV"),datedebut="2011-01-01",datefin="2011-12-31")
  r_mig_mult<-charge(r_mig_mult)
  # launching charge will also load classes associated with the report
  # e.g. report_ope, report_df, report_dc
  r_mig_mult<-connect(r_mig_mult)
  # calculations 
  r_mig_mult<-calcule(r_mig_mult,silent=TRUE)
```

**Comment by SebastienGrall** [comment]
No, I still have this message : "Some data differ between t_reportjournalier_bjo table, this means that they have been changed after the last report_mig was run, do you want to load them again for calculation ?"

my code : 
```r
r_mig_interannual<-new("report_mig_interannual")
r_mig_interannual<-choice_c(r_mig_interannual,
                            dc=c(102),
                            taxa=c("Anguilla anguilla"),
                            stage=c("4"),
                            anneedebut="2014",
                            anneefin="2018",
                            silent=TRUE)
r_mig_interannual<-charge(r_mig_interannual)
r_mig_interannual<-connect(r_mig_interannual,check=TRUE)	
r_mig_interannual<-calcule(r_mig_interannual,silent=TRUE)
```

**Comment by cedricbriandgithub** [comment]
Thank you, the check argument in `r_mig_interannual` should help you there. But you need to re-run the class with `check = FALSE ` if you have changes in your database and want to see the data updated. Behind the scene, the r_mig_interannual class runs the r_mig_mult class for all years. The r_mig_mult class writes the t_bilanjournalier_bjo and the t_bilanmensuel_bme tables in your schema. Those are used by the r_mig_interannual class to process interannual information. Does that answer your question ? If not I will open an issue.

**Comment by SebastienGrall** [comment]
Yes, Thanks!
