### ISSUE TITLE
Report mig interannual

### ISSUE THREAD

**Issue by SebastienGrall** [MarionLegrandLogrami/stacomiR#3]
Hey,

I want to run a report mig interannual using this code : 

`r_mig_interannual<-new("report_mig_interannual")
r_mig_interannual<-choice_c(r_mig_interannual,
                            dc=c(101),
                            taxa=c("Silurus glanis"),
                            stage=c("5"),
                            anneedebut="2008",
                            anneefin="2018",
                            silent=TRUE)
r_mig_interannual<-charge(r_mig_interannual)
r_mig_interannual<-connect(r_mig_interannual,check=TRUE)	
r_mig_interannual<-calcule(r_mig_interannual,silent=TRUE)`

I've warning messages : 
`Warning messages:
1: In .local(object, ...) :
  Attention, year 2008 is not available in the database, available years : none
2: In .local(object, ...) :
  Attention, year 2018 is not available in the database, available years : none
> r_mig_interannual<-charge(r_mig_interannual)
[1] Ecriture du bilan Migration Interannuelle dans l'environnement envir_stacomi : écrire bmi=get('report_mig_interannual',envir_stacomi) 
> r_mig_interannual<-connect(r_mig_interannual,check=TRUE)	
Error in sum(bjo_valeur) : invalid 'type' (character) of argument
> r_mig_interannual<-calcule(r_mig_interannual,silent=TRUE)
Error in .local(object, ...) : 
  No rows in report_mig_interannual@data, nothing to run calculations on, you should run a report_mig_mult on this dc first`

Even if I run a report mig mult like this one : 

`r_mig_mult=new("report_mig_mult")
r_mig_mult=choice_c(r_mig_mult,
                    dc=c(101),
                    taxa=c("Silurus glanis"),
                    stage=c(5),datedebut="2018-01-01",datefin="2018-12-31")
r_mig_mult<-charge(r_mig_mult)
r_mig_mult<-connect(r_mig_mult)
r_mig_mult<-calcule(r_mig_mult,silent=TRUE)`

Any idea? Thanks ;-)

**Comment by SebastienGrall** [comment]
It's working for other taxa...

**Comment by cedricbriandgithub** [comment]
Hi Sebastien
Apparently this is not an issue with writing permissions, we've had that before 
Try stage=c(5)

Cédric

**Comment by SebastienGrall** [comment]
Hi,
Already try but same issue...
I've this data when I write `bmi=get('report_mig_interannual',envir_stacomi) ` : 

An object of class "report_mig_interannual"
Slot "dc":
An object of class "ref_dc"
Slot "dc_selectionne":
[1] 101

Slot "ouvrage":

[1] 1

Slot "station":
[1] "POSES"

Slot "data":
   dc dis_date_creation dis_date_suppression df                   dis_commentaires dif_ouv_identifiant
1 101        2007-10-01                 <NA>  1               Video usine RG Poses                   1
2 102        2014-01-01                 <NA>  2 Cuve piège rampe anguille RG Poses                   1
3 103        2016-01-01                 <NA>  3             Video ecluse RD1 Poses                   2
4 104        2016-01-01                 <NA>  4   Rampe à anguille Ecluse RD Poses                   2
5 105        2016-01-01                 <NA>  3             Vidéo ecluse RD2 Poses                   2
6 106        2017-03-01                 <NA>  5         Vidéo RD Poste 1 Carandeau                   3
7 107        2017-03-01                 <NA>  5         Vidéo RD Poste 2 Carandeau                   3
                         ouv_libelle        df_code          dc_code                dif_localisation dif_orientation
1     Usine hydroelectrique de Poses   PAB_RG_USINE   VIDEO_RG_USINE   Passe à bassins RG côté usine          MONTEE
2     Usine hydroelectrique de Poses  RAMP_RG_USINE   PIEGE_RG_USINE  Rampe à anguille RG Côté usine          MONTEE
3 Ecluse d'Amfreville sous les Monts  PAB_RD_ECLUSE VIDEO_RD1_ECLUSE  Passe à bassins RD côté Ecluse          MONTEE
4 Ecluse d'Amfreville sous les Monts RAMP_RD_ECLUSE  PIEGE_RD_ECLUSE Rampe à anguille RD côté Ecluse          MONTEE
5 Ecluse d'Amfreville sous les Monts  PAB_RD_ECLUSE VIDEO_RD2_ECLUSE  Passe à bassins RD côté Ecluse          MONTEE
6                          Carandeau   PAB_RD_CARAN  VIDEO_RD1_CARAN    Passe à bassins RD Carandeau          MONTEE
7                          Carandeau   PAB_RD_CARAN  VIDEO_RD2_CARAN    Passe à bassins RD Carandeau          MONTEE
                     type_df                  type_dc sta_code
1 Passe à bassins successifs Analyse visuelle d'image    POSES
2                      Rampe                 Piégeage    POSES
3 Passe à bassins successifs Analyse visuelle d'image    POSES
4                      Rampe                 Piégeage    POSES
5 Passe à bassins successifs Analyse visuelle d'image    POSES
6      Passe à ralentisseurs Analyse visuelle d'image    CARAN
7      Passe à ralentisseurs Analyse visuelle d'image    CARAN


Slot "taxa":
An object of class "ref_taxa"
Slot "data":
   tax_code  tax_nom_latin tax_nom_commun tax_ntx_code tax_tax_code
23     2238 Silurus glanis   Silure glane           15           NA


Slot "stage":
An object of class "ref_stage"
Slot "data":
  std_code std_libelle
1        5      Adulte


Slot "data":
data frame with 0 columns and 0 rows

Slot "start_year":
An object of class "ref_year"
Slot "data":
[1] bjo_annee
<0 rows> (or 0-length row.names)

Slot "annee_selectionnee":
[1] 2008


Slot "end_year":
An object of class "ref_year"
Slot "data":
[1] bjo_annee
<0 rows> (or 0-length row.names)

Slot "annee_selectionnee":
[1] 2018


Slot "calcdata":
list()


Sébastien

**Comment by cedricbriandgithub** [comment]
Sebastien, I need to test this, can you send a dump of your shema ?
Sorry I'm a bit slow to answer

**Comment by SebastienGrall** [comment]
Yes I can!
No problem this is not urgent.

**Comment by cedricbriandgithub** [comment]
I have fixed that bug, when there are no lines in the dataset it's interpreted as a character and now it fires an error.
